### PR TITLE
Add Symbol Editor to Pro Tab

### PR DESCRIPTION
**Pull request by csmoore**
1. Add Symbol Editor to Tab - #20
2. Update batch file so it also works with a local-user (rather than just "all users") install (mine is a local-user install)
3. Fix toolbar name - #18 
4. Add uninstall script/bat

### CODE REVIEW

**Comment by csmoore** [comment]
I assigned PR to @dhagens to review and merge since he did the ArcGISProAddin - but let me know if I should assign to someone else.

The included fix to the broken Pro addin toolbar install bat ( #18 ) should probably be done soon-ish though

**Comment by dhagens** [comment]
I'll review this now.  #18 was fixed yesterday.  I tested this morning.  I'll have @pshowalter verify and close.

**Comment by csmoore** [comment]
@dhagens - confused - #18 and [this file](https://github.com/Esri/military-tools-for-arcgis/blob/dev/source/MilitaryToolsToolbar/ArcGISProAddinMAToolbar/InstallMilitaryToolsFoArcGISPro.bat) was fixed in PR other than this one?

**Comment by dhagens** [comment]
Yes, I fixed the naming issue yesterday.  You can verify build last night.  Tested this morning and everything was fine.  Your fix was the same so just overwrote what was already in there.

**Pull request merged**
