### PR TITLE
Revert "Fix bug reported in #28"

### PR DESCRIPTION
**Pull request by pshowalter**
Reverts Esri/military-tools-for-arcgis#29
Still failing:
capture

### CODE REVIEW

**Comment by pshowalter** [comment]
@csmoore still failing

**Comment by csmoore** [comment]
@pshowalter - looks like you are getting further, but that message is normal/expected if for some reason one of those components is not installed - can you try the [install-all](https://github.com/Esri/military-tools-for-arcgis/blob/dev/source/MilitaryToolsToolbar/ArcMapAddinMAToolbar/InstallMilitaryToolsForArcMap.bat) script before testing the uninstall.

**Comment by pshowalter** [comment]
@csmoore 

InstallMilitaryToolsForArcMap.bat works w/o issue, although it uses /s - so maybe something gets missed.  The UN-InstallMilitaryToolsForArcMap.bat throws four "Uninstallation failed." messages at each call to 

``
ESRIRegAddIn.exe  {xxx} /u 
``
Does the guid being used need to be verified?

It appears that the Install'er overwrites, previous so things seem work, but can't uninstall cleanly.

**Comment by pshowalter** [comment]
The quotes fixed some of the script and should be committed.

**Comment by csmoore** [comment]
@pshowalter - I tested the uninstall/install scripts from {buildserver}\MilitaryToolsForArcGIS\_current (this is where they are usually installed from anyway) - & they seem to work as expected. So perhaps there is an issue with the addins not being installed as expected - I would remove the `/s` to determine which one.

Oddly the build server version of UN-installArcmapAddins.bat already had this fix so not sure where the build server was pulling that file from, probably not GitHub.

**Comment by pshowalter** [comment]
I removed "/s" and all AddIn's install w/o issue.  I can reproduce this on 3 machines now,  using 10.4 and 10.4.1.

**Comment by csmoore** [comment]
I was testing using 10.3.1 so it may be related to the new version

**Comment by pshowalter** [comment]
Do you recommend a ew issue?  It looks like the original issue related to the quotes has made it into the "_current" folder.

**Pull request closed without merging**
